import type { ReportExportInput } from "./excel";

function esc(v: any): string {
  if (v === null || v === undefined) return "";
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** Build the CSV body — totals row matches Excel exporter. */
export function buildReportCsv(input: ReportExportInput): string {
  const { title, columns, rows, totalsRow, meta } = input;
  const lines: string[] = [];
  lines.push(esc(meta.company));
  lines.push(esc(title));
  if (meta.dateRange) lines.push(esc(`Date range: ${meta.dateRange.from || "—"} to ${meta.dateRange.to || "—"}`));
  if (meta.filters?.length) lines.push(esc(`Filters: ${meta.filters.map(f => `${f.label}=${f.value}`).join(", ")}`));
  lines.push(esc(`Generated by: ${meta.user} at ${meta.generatedAt}`));
  lines.push("");
  lines.push(columns.map(c => esc(c.header)).join(","));
  rows.forEach(r => lines.push(columns.map(c => esc(r[c.key])).join(",")));
  if (totalsRow) {
    lines.push(columns.map((c, i) => esc(totalsRow[c.key] ?? (i === 0 ? "TOTAL" : ""))).join(","));
  }
  return lines.join("\n");
}

export function exportReportToCsv(input: ReportExportInput) {
  const blob = new Blob([buildReportCsv(input)], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const stamp = new Date().toISOString().slice(0, 10);
  a.href = url;
  a.download = `${input.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-${stamp}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export function copyReportToClipboard(input: ReportExportInput) {
  const { columns, rows, totalsRow } = input;
  const tsv = [
    columns.map(c => c.header).join("\t"),
    ...rows.map(r => columns.map(c => String(r[c.key] ?? "")).join("\t")),
    ...(totalsRow ? [columns.map((c, i) => String(totalsRow[c.key] ?? (i === 0 ? "TOTAL" : ""))).join("\t")] : []),
  ].join("\n");
  return navigator.clipboard.writeText(tsv);
}
