import * as XLSX from "xlsx";
import type { ReportMeta } from "./meta";

export interface ReportColumn {
  key: string;
  header: string;
  /** Numeric → right-align + currency format. */
  type?: "text" | "number" | "currency" | "date";
}

export interface ReportExportInput {
  title: string;
  sheetName?: string;
  columns: ReportColumn[];
  rows: Record<string, any>[];
  /** Totals row values keyed by column.key; non-numeric columns can be omitted. */
  totalsRow?: Record<string, any>;
  meta: ReportMeta;
}

const CURRENCY_FMT = "#,##0.00";
const DATE_FMT = "yyyy-mm-dd";

/** Build a workbook that matches the on-screen totals row. */
export function buildReportWorkbook(input: ReportExportInput): XLSX.WorkBook {
  const { title, columns, rows, totalsRow, meta } = input;
  const ws: XLSX.WorkSheet = {};
  const colCount = columns.length;
  const endCol = XLSX.utils.encode_col(colCount - 1);

  // Header block (rows 1..5)
  const headerLines = [
    meta.company,
    title,
    meta.dateRange ? `Date range: ${meta.dateRange.from || "—"} to ${meta.dateRange.to || "—"}` : null,
    meta.filters && meta.filters.length
      ? `Filters: ${meta.filters.map(f => `${f.label}=${f.value}`).join(", ")}`
      : null,
    `Generated by: ${meta.user}   at ${meta.generatedAt}`,
  ].filter(Boolean) as string[];

  headerLines.forEach((text, i) => {
    const addr = `A${i + 1}`;
    ws[addr] = { t: "s", v: text, s: { font: { bold: i < 2 } } };
  });

  // Blank row, then column headers at row = headerLines.length + 2
  const headerRowIdx = headerLines.length + 1; // 0-indexed for r in cell ref; row number = headerRowIdx + 1
  columns.forEach((c, ci) => {
    const addr = XLSX.utils.encode_cell({ r: headerRowIdx, c: ci });
    ws[addr] = { t: "s", v: c.header, s: { font: { bold: true } } };
  });

  // Data rows
  rows.forEach((row, ri) => {
    columns.forEach((col, ci) => {
      const addr = XLSX.utils.encode_cell({ r: headerRowIdx + 1 + ri, c: ci });
      writeCell(ws, addr, row[col.key], col.type);
    });
  });

  // Totals row
  if (totalsRow) {
    const totalsR = headerRowIdx + 1 + rows.length;
    columns.forEach((col, ci) => {
      const addr = XLSX.utils.encode_cell({ r: totalsR, c: ci });
      const v = totalsRow[col.key];
      if (v === undefined || v === null || v === "") {
        if (ci === 0) ws[addr] = { t: "s", v: "TOTAL", s: { font: { bold: true } } };
        return;
      }
      writeCell(ws, addr, v, col.type);
      const cell = ws[addr];
      if (cell) cell.s = { ...(cell.s || {}), font: { bold: true } };
    });
  }

  // Range + freeze + auto width
  const lastR = headerRowIdx + 1 + rows.length + (totalsRow ? 1 : 0);
  ws["!ref"] = `A1:${endCol}${lastR}`;
  ws["!freeze"] = { xSplit: 0, ySplit: headerRowIdx + 1 };
  ws["!cols"] = columns.map(c => ({
    wch: Math.min(
      40,
      Math.max(
        c.header.length + 2,
        ...rows.slice(0, 200).map(r => String(r[c.key] ?? "").length + 2),
      ),
    ),
  }));

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, input.sheetName || "Report");
  return wb;
}

function writeCell(ws: XLSX.WorkSheet, addr: string, value: any, type?: ReportColumn["type"]) {
  if (value === null || value === undefined || value === "") return;
  if (type === "number" || type === "currency") {
    const n = Number(value);
    if (!Number.isFinite(n)) { ws[addr] = { t: "s", v: String(value) }; return; }
    ws[addr] = { t: "n", v: n, z: type === "currency" ? CURRENCY_FMT : undefined };
  } else if (type === "date") {
    ws[addr] = { t: "s", v: String(value), z: DATE_FMT };
  } else {
    ws[addr] = { t: "s", v: String(value) };
  }
}

/** Download a single-sheet report as .xlsx. */
export function exportReportToExcel(input: ReportExportInput) {
  const wb = buildReportWorkbook(input);
  const stamp = new Date().toISOString().slice(0, 10);
  const fname = `${slug(input.title)}-${stamp}.xlsx`;
  XLSX.writeFile(wb, fname);
}

function slug(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}
